### ISSUE TITLE
"Fix Model" does not work with this kind of rigging

### ISSUE THREAD

**Issue by SimonBestia** [teamneoneko/Cats-Blender-Plugin#135]
Before potentially wasting your time, I'll mention the models in question are in .nif format. Blender supports them out of the box, so I'm not sure if this plugin requires specifically the models listed or if others are fine.

**Description of issue:** 
"Fix MMD Model" fails to detect most of the bones from the armature of models used in the videogame BULLY.
The game uses .nif models, which are not listed among the supported model list, but I think the culprit is the way the rigging is on the models. It's pretty unconventional compared to other games' models I've seen.
I'll be attaching a vanilla .nif, and a screenshot of my case.

**Blender Version:**
3.6

**Cats Version:**
3.6.7.6

**OS:**
Windows 11

**Steps to re-produce:**
Press "Fix Model" on the provided model. The plugin will fail to fix it, and prompt to share it.

Out of the box, the rigging of the BULLY models looks something like this:
![image](https://github.com/teamneoneko/Cats-Blender-Plugin-Unofficial-/assets/36112411/00166bff-71ff-4ff3-92db-94722a1b007b)

Here is a vanilla .nif model, with the .nft for textures, and extracted textures, for convenience:
[B_Buzz.zip](https://github.com/user-attachments/files/16070591/B_Buzz.zip)

**Comment by RinaDev-xyz** [comment]
As you stated, this file type and armature struture is not supported by Cats.

Fix model button is only intended to fix MMD or VRM files that are not setup for Unity and is not intended for other files formats.
By default blender also does not support .nif files and you need a addon for .nif files to be imported, which means cats would need extra functionailty to support that said addon. 

Was confused on why you think blender support nif natively as I had to download nif tools to be able to import. 

Due to the amount of work it would most likely take to support this file format we would not add it to cats as cats is basically only being maintained now. You can suggest adding this format to the upcoming avatar tools, however I can't promise it would be added: https://github.com/teamneoneko/Avatar-Toolkit

Due to these reasons this issue will be closed and this is marked as won't fix. But thanks for filling out with the correct template!

**Comment by SimonBestia** [comment]
I could've sworn the addon was part of the default library but I guess I remembered wrong.
Thanks for looking into it, though!
