### ISSUE TITLE
Missing Sidebar named "MISC" in Blender 3.6 with CATS 3.6.7.6

### ISSUE THREAD

**Issue by boyaom** [teamneoneko/Cats-Blender-Plugin#146]
Name of issue - Missing Sidebar named "MISC" in Blender 3.6 with CATS 3.6.7.6

Description of issue:
I am encountering an issue where the "MISC" Sidebar, which is typically present in official version, is missing from my Blender 3.6.
The expected appearance of the "MISC" Sidebar is demonstrated in the attached
 ![a](https://github.com/user-attachments/assets/2b165deb-a26f-4f5a-9578-d6fe1f839446)
, but instead, my Sidebar view looks like this 
![b](https://github.com/user-attachments/assets/ebc1e577-55e4-47a8-806b-c794c02d5a29)

Blender Version: 3.6
Cats Version: 3.6.7.6
OS: Windows 10/11
Steps to reproduce: Open Blender 3.6 and install CATS 3.6.7.6

Suggestion:
Upon investigating, I have found that modifying the inheritance of the MMDViewPanel and MMDSDEFPanel classes in the extern_tools\mmd_tools_local\panels\view_prop.py file might resolve this issue. Specifically, changing their base classes from (_PanelBase) to (_PanelBase, Panel) has restored the "MISC" Sidebar for me, as shown in this
![c](https://github.com/user-attachments/assets/79b9e93d-83fb-4ed3-b7ae-db99959e5577)
However, please note that I have only tested this solution in my current Blender and CATS Tools versions, and I have not verified its compatibility with other versions.

**Comment by RinaDev-xyz** [comment]
Hi there, 

Before posting about MMD Tools issues please ensure you test the standalone version of MMD Tools before you post an issue to cats. 

MMD Tools is a 3rd party addon which is NOT maintained by Cats in anyway and Cats DOES NOT touch mmd tools UI. All cats does is rename MMD Tools classes and adds mmd_tools_local to help fix issues with classes when a user has MMD Tools standalone installed. Cats then only uses some of the functions to provide some of it's own functions. We have not edited the UI in any way.

I did quickly test the standalone version and this issue is in the latest version of MMD Tools for Blender 3.6. This has nothing to do with Cats. Please report this issue to MMD Tools instead: https://github.com/UuuNyaa/blender_mmd_tools/issues

The image below shows you no misc tab with the standalone version of MMD Tools:
![Screenshot from 2024-07-18 20-54-00](https://github.com/user-attachments/assets/8d9e51d4-ee3e-4c1f-bfb9-3876fa3f96d1)

Due to this not being a cats issue and due to our policy, this issue will be closed and won't be fixed by us, if you feel like this is a mistake feel free to re-open.

If this issue get's fixed in MMD Tools, feel free to open a new issue to let us know and we will update out local version of MMD Tools. 

Thanks

**Comment by RinaDev-xyz** [comment]
Also looking at there issue tracker this was already reported to them:

https://github.com/UuuNyaa/blender_mmd_tools/issues/140

This seems like a change in MMD Tools, the author told the user to look at this: https://mmd-blender.fandom.com/wiki/MMD_Tools/Release_Notes#UI_improvements_and_changes

The shading options have been moved see below image to where there moved shading too. This is NOT an issue and is an intended change.
![UI_changes-v2 0-New_View3D_Shading](https://github.com/user-attachments/assets/d77263a5-52c0-402a-94f5-84f3139b2895)


Please ensure you look at a plugin wiki before opening issues, thanks.
