### ISSUE TITLE
Custom Model Creation: If armature To Merge is a child of the Base armature, CATS reports an error

### ISSUE THREAD

**Issue by DrSakuu** [teamneoneko/Cats-Blender-Plugin#174]
I have a collar armature parented to the neck bone of the base armature, but now I want to merge the two armatures. When I try to use Merge Armatures in Custom Model Creation, CATS wants me to use the "Fix Model" feature, which should never be recommended. The solution is to clear the parent relation first and then merge, but the tool should do that automatically.

Blender Version: 4.2.1
Cats Version: 4.2.1.2
OS: Windows 11

Steps to re-produce:

1. Parent an armature to the base armature you're trying to merge to.
2. Try to use Merge Armatures to attach it to a bone on the base armature and then CATS wants you to use the "Fix Model" feature.
3. Unparent the armature To Merge and then Merge Armatures works without errors.

![20240902_142345-DLJ3-blender](https://github.com/user-attachments/assets/aa110628-5d77-410b-9e47-77970054b3e6)
![20240902_140200-wLwQ-blender](https://github.com/user-attachments/assets/fb3c4531-8586-4d87-8ea8-195d9857c356)

**Comment by RinaDev-xyz** [comment]
Hello,

From my understanding (and I will need to review the code to confirm), this message should only appear if a non-standard armature is detected. This suggests that your armature isn't standard, or CATS doesn't recognize it as such.

I will investigate this issue further and consider changing the warning to something like:

"Non-standard armature detected. If this is an MMD/VRM model or a model not set up for Unity, please consider using the 'Fix MMD Model' function. If not, press OK to continue with the merge."

This approach would allow users to proceed if they press OK instead instead of just cancelling the merge.

**Comment by DrSakuu** [comment]
I only tested this just now, but I get the error `AttributeError: module 'bl-ext.user-default.cats_blender_plugin.tools.common' has no attribute 'show_warning'` on Cats version 4.2.1.3
![20240913_175102-v3yO-blender](https://github.com/user-attachments/assets/7ae0bf54-315a-4697-8995-36f0b8ff96a2)
