### ISSUE TITLE
error report for 2days ago update : I can't use fix button.

### ISSUE THREAD

**Issue by js889** [teamneoneko/Cats-Blender-Plugin#183]
I read roughly rule of github. 
But, maybe I asked useless question.
![240911-2-](https://github.com/user-attachments/assets/3d7f2587-dc4e-492e-a46c-0af71bbdd4f3)
![240911-1-](https://github.com/user-attachments/assets/56276f09-ae26-4299-979b-1662111bb0bb)
![240911-3-](https://github.com/user-attachments/assets/8a6f9b2d-bd29-467d-bf49-31ba6cd9b661)

I'm begginer of blender. But It's not my first tool for 3D.
I tried to both, old ver and recent ver for cat plugin.
I just first install blender yesterday. Only used 2 plugin. Vrm and Cat. 
And I tested to both laptop and desktop.
My os is win10, both.

I just wanted to made fbx file as like tutorial vrm to fbx. 
but I made texture ripped off and awful fbx. 

Thanks in advance.

**Comment by RinaDev-xyz** [comment]
This is a MMD tools error and not a cats one.

Cats uses MMD Tools for several of it's functions including the fix button, this is a 3rd party plugin which cats packages with it.

First of all make sure you restarted blender before using the plugin.

If that fails it could be because mmd tools can't find the armature or root object (root) this is most likely because the armature and or bones are not named in a conventional manner my advice would be to make sure the bones are correctly named. Failing this make sure all items are unhidden and make sure there is a root object. 

If all else fails please report the issue to MMD Tools as we can't do anything over with Cats to fix it.

**Comment by js889** [comment]
Whatever thanks for reply.  Sorry for late.
