### ISSUE TITLE
fix model button crashes blender

### ISSUE THREAD

**Issue by Andy-Dandy26** [teamneoneko/Cats-Blender-Plugin#199]
Issue Title: fix model button crashes blender

Description of Issue:
When clicking 'Fix MMD model', the process causes Blender to crash instantly with no crash or bug report.

Blender Version:
4.3.0

Cats Version:
4.3.0

Operating System:
Windows 10

Steps to Reproduce:

[First step] Open blender. In object mode, Select the metarig object.
[Second step] Click the 'Fix MMD Model' button. Blender will crash if you do this.

**Comment by RinaDev-xyz** [comment]
As stated on the discord metarigs or rigify models are not supported by the fix mmd button and never truly have.

There has never been any code which allowed the metarigs or rigify rigs to be fixed via the fix model button. It was just in the past the rigify system was more simple and happened to just work fine with cats fix model which was more lucky then anything.

However blender changed alot of things with rigify since blender 4.0 and broke this compatibility, as fix model was never targeted towards those rigs and was always for mmd and vrm models (with gmod compatible scripts) and not for this use case, this issue will not be fixed.

However I will fix the crash issue as it shouldn't just crash and will have cats tell users the fix mmd model button is not meant to be used on rigify models.

If your looking for a rigify to unity system there are plugins which does this.

**Comment by Andy-Dandy26** [comment]
that's weird, I'm following a tutorial where the youtuber used it. maybe I used the wrong rig? in any case. thank you for taking the time to respond.

**Comment by RinaDev-xyz** [comment]
Alot of YouTubers didn't understand what the fix model button did and never followed official advice. The fix model button can break non mmd and vrm models at times. Official advice was not to use it on non mmd, vrm or gmod models.

At a good guess at the time of when that video was made the fix model button was working with rigify but again, there was never any code which interacts with rigify it was pure luck that it worked. It was never made for that use case hence why we finally renamed it to fix mmd model.

After i fix the crash it may still work, however the crash is proving difficult to track down at the minute.

**Comment by Andy-Dandy26** [comment]
Fair enough. After watching the tutorial further, it appears to have broken his rig slightly and he needed to fix it. And then re-exported it the normal way anyway so it was entirely pointless. 😅

**Comment by RinaDev-xyz** [comment]
Sounds about right lol, I update this post once I found a fix fir the crash

**Comment by RinaDev-xyz** [comment]
This issue will be closed.

I am unable to fix the crash with rigify and metarigs, blender has changed way too much with rigify and would need major changes to Cats side to support it correctly and properly. 

Avatar Toolkit will support Rigify and metarigs in the future so there is no point spending hours of work on Cats for this when it was never supported.

Instead if a user tries and use fix mmd model on a metarig as long as the user hasn't change bones names, cats will now tell the user the action is not supported and will cancel the operations.

This is deemed as will not fixed due to this. 

Please see this issue on Avatar Toolkit re us adding this to avatar toolkit: https://github.com/teamneoneko/Avatar-Toolkit/issues/28

**Comment by Andy-Dandy26** [comment]
Understandable. Maybe post this issue somewhere prominent in the discord in case new users fall down the same rabbit hole.

**Comment by RinaDev-xyz** [comment]
It will be added to the wiki in due course, plus the crash should not happen anymore as we will prevent users from even using fix mmd on those type of rigs.
