### ISSUE TITLE
Issue's With Parenting Bones

### ISSUE THREAD

**Issue by KannaKamui6969** [teamneoneko/Cats-Blender-Plugin#46]
I've been having a problem with merging bone's and im not sure if its my blender or the script, I am using blender 4.0 cat's and heres a picture of the issue.

![image_2024-02-10_052115424](https://github.com/Yusarina/Cats-Blender-Plugin-Unofficial-/assets/74091179/b81dd711-8122-4b21-8085-e0483b11a8b2)

**Comment by KannaKamui6969** [comment]
Sorry, I found a way around it.

**Comment by RinaDev-xyz** [comment]
I will keep this open as it's still an issue that I will look into.

**Comment by RinaDev-xyz** [comment]
Hi there,

This error is caused because the bone is not found in the parenting list, I have released a possible fix for this issue on the blender 4.0 and 3.6 dev branch, however I got to be honest the entire system kinda needs re-do as it doesn't count for several issues.

I have been slowly re-writing and cleaning up several parts of cats in recent weeks however currently most changes are only in the blender 3.6 version of cats as that is my priority right now as blender 3.6 is the current Long term support version of blender.

The changes on the 3.6 version will eventually come over to 4.0 in the next week or so.

**Comment by KannaKamui6969** [comment]
Oh alrighty! Sorry as soon as I found a slight workaround for my model I kinda thought this would be useless but guess not Thanks! I'm also glad to see someone is working on getting the plugin updated to newer versions of blender I appreciate the hard work ^^

**Comment by RinaDev-xyz** [comment]
Closed as fixed is now released on 3.6.6.1
