### ISSUE TITLE
Texture missing when exporting on FBX

### ISSUE THREAD

**Issue by NyutDaulkel** [teamneoneko/Cats-Blender-Plugin#95]
Sup! I'm new to the plugin and I followed a video to "simply export vrm to fbx", but the video mentions activating a "Fix textures" option which is not found in my unofficial version of CATS, that's something I'm missing or the option is simply not there?
Do I need an extra plugin or do extra steps?

Video tutorial (JustANoobArtist):
![1](https://github.com/unofficalcats/Cats-Blender-Plugin-Unofficial-/assets/150964844/c4bf23d6-89f0-47ca-912b-c798613d4344)

My plugin: 
![2](https://github.com/unofficalcats/Cats-Blender-Plugin-Unofficial-/assets/150964844/00931f8f-c4e6-47e6-9be0-bee6d152c01b)

ty!

**Comment by RinaDev-xyz** [comment]
Please ensure you read the wiki before posting in the future as your answer in this case is in there: https://github.com/unofficalcats/Cats-Blender-Plugin-Unofficial-/wiki/Features

It has been moved to the MMD Options as a separate button. Also I not sure what version of Cats you are using, but this isn't the unofficial cats in the second image.

The Unofficial version of cats has changed a bit compared to the official version so most YouTube videos are out of date. This YouTube video is also using the main branch of the official cats which is more outdated then the dev branch of the official cats (Atleast 3 or 4 years since the main branch got updated compared to the 1 year the dev branch was last updated).

Please close the issue if this has solved the problem.

**Comment by RinaDev-xyz** [comment]
In fact from your second image you are using the official cats which we do not provide any support what so ever for and you are using main branch to be exact, we don't provide support for the official cats so this issue will be closed. If you need help with the official cats please go to their discord server or download our unofficial version which is what this github is for.

It seems you are on out discord server, I pinged you in the cat-help channel with more info.

Thanks

**Comment by RinaDev-xyz** [comment]
I going to reply here with the resolution to this issue. As it turns out the user was using this version of cats but did have the official one installed before hand. in between switching versions the user didn't restart blender, therefor there created some kind of hybrid monster of cats which caused the confusion here. (Cats had half the official version functions and half of the unofficial ones functions).

Solution is to restart blender if you changed plugins so that blender doesn't get confused and create werid hybrid plugins lol, just for future reference in case anyone is searching for a solution.
